// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.DeptComments;
import java.io.Serializable;

privileged aspect DeptComments_Roo_Serializable {
    
    declare parents: DeptComments implements Serializable;
    
    private static final long DeptComments.serialVersionUID = 1L;
    
}
