// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.PlayData;
import java.io.Serializable;

privileged aspect PlayData_Roo_Serializable {
    
    declare parents: PlayData implements Serializable;
    
    private static final long PlayData.serialVersionUID = 1L;
    
}
