// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.RecommendClass;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RecommendClass_Roo_Configurable {
    
    declare @type: RecommendClass: @Configurable;
    
}
