// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.ScoreIndicator;
import java.io.Serializable;

privileged aspect ScoreIndicator_Roo_Serializable {
    
    declare parents: ScoreIndicator implements Serializable;
    
    private static final long ScoreIndicator.serialVersionUID = 1L;
    
}
