// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.Score;
import java.io.Serializable;

privileged aspect Score_Roo_Serializable {
    
    declare parents: Score implements Serializable;
    
    private static final long Score.serialVersionUID = 1L;
    
}
