// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.Status;
import java.io.Serializable;

privileged aspect Status_Roo_Serializable {
    
    declare parents: Status implements Serializable;
    
    private static final long Status.serialVersionUID = 1L;
    
}
