// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.entites;

import com.sx.tv.entites.Type;
import java.io.Serializable;

privileged aspect Type_Roo_Serializable {
    
    declare parents: Type implements Serializable;
    
    private static final long Type.serialVersionUID = 1L;
    
}
