// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.view;

import com.sx.tv.view.SearchTV;
import java.io.Serializable;

privileged aspect SearchTV_Roo_Serializable {
    
    declare parents: SearchTV implements Serializable;
    
}
