// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sx.tv.view;

import com.sx.tv.entites.TVShowData;

privileged aspect TVShowData_Roo_JavaBean {
    
   
}
